<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="3447" started-at="2020-02-09T16:42:25 IST" finished-at="2020-02-09T16:42:29 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="3262" started-at="2020-02-09T16:42:25 IST" finished-at="2020-02-09T16:42:28 IST">
      <class name="etoETestcases.BankManagerLoginTest">
        <test-method status="PASS" signature="loginAsBankManager()[pri:0, instance:etoETestcases.BankManagerLoginTest@366647c2]" name="loginAsBankManager" duration-ms="3198" started-at="2020-02-09T16:42:25 IST" finished-at="2020-02-09T16:42:28 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- etoETestcases.BankManagerLoginTest -->
    </test> <!-- Test -->
    <test name="Add Customer Test" duration-ms="128" started-at="2020-02-09T16:42:29 IST" finished-at="2020-02-09T16:42:29 IST">
      <class name="etoETestcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:etoETestcases.AddCustomerTest@69e1dd28]" name="setUp" is-config="true" duration-ms="19082" started-at="2020-02-09T16:42:06 IST" finished-at="2020-02-09T16:42:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:etoETestcases.AddCustomerTest@69e1dd28]" name="addCustomer" duration-ms="0" started-at="2020-02-09T16:42:29 IST" data-provider="getData" finished-at="2020-02-09T16:42:29 IST">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 1
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:820)
at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
at etoETestcases.AddCustomerTest.getData(AddCustomerTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:etoETestcases.AddCustomerTest@69e1dd28]" name="tearDown" is-config="true" duration-ms="4338" started-at="2020-02-09T16:42:29 IST" finished-at="2020-02-09T16:42:33 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- etoETestcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Suite -->
</testng-results>
